# Generated by Django 4.2 on 2023-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=15)),
                ('phno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=510)),
                ('prodDescription', models.CharField(max_length=515)),
                ('prodImage', models.CharField(max_length=515)),
                ('prodPrice', models.IntegerField()),
            ],
        ),
    ]
